version: '3.8'

services:
  ml-service:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./reports:/app/reports
      - ./mlruns:/app/mlruns
    environment:
      - MLFLOW_TRACKING_URI=sqlite:///mlflow.db
      - PYTHONPATH=/app
    command: python src/api/app.py

  mlflow-ui:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/app/mlruns
      - ./mlflow.db:/app/mlflow.db
    environment:
      - MLFLOW_TRACKING_URI=sqlite:///mlflow.db
    command: mlflow ui --host 0.0.0.0 --port 5000

  training:
    build: .
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./reports:/app/reports
      - ./mlruns:/app/mlruns
    environment:
      - MLFLOW_TRACKING_URI=sqlite:///mlflow.db
      - PYTHONPATH=/app
    command: python src/models/train.py