version: '3.8'

services:
  ml-api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./reports:/app/reports
    environment:
      - PYTHONPATH=/app/src
    command: uvicorn src.api.app:app --host 0.0.0.0 --port 8000 --reload
    
  mlflow-ui:
    image: python:3.9-slim
    ports:
      - "5000:5000"
    working_dir: /app
    volumes:
      - .:/app
    command: |
      bash -c "pip install mlflow && mlflow ui --host 0.0.0.0 --port 5000 --backend-store-uri sqlite:///mlflow.db"
    
  monitoring:
    build: .
    volumes:
      - .:/app
    working_dir: /app
    command: python src/monitoring/drift_detection.py
    profiles:
      - monitoring